apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-order
  labels:
    app: work-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work-order
  template:
    metadata:
      labels:
        app: work-order
    spec:
      containers:
        - name: work-order
          image: username/work-order:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5