server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: work-order
          uri: http://localhost:8081
          predicates:
            - Path=/workOrders/**, 
        - id: product
          uri: http://localhost:8082
          predicates:
            - Path=/productions/**, 
        - id: master
          uri: http://localhost:8083
          predicates:
            - Path=/equipment/**, /workers/**, /materials/**, 
        - id: dashboard
          uri: http://localhost:8084
          predicates:
            - Path=, /dashboards/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: work-order
          uri: http://workOrder:8080
          predicates:
            - Path=/workOrders/**, 
        - id: product
          uri: http://product:8080
          predicates:
            - Path=/productions/**, 
        - id: master
          uri: http://master:8080
          predicates:
            - Path=/equipment/**, /workers/**, /materials/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, /dashboards/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
